### ISSUE TITLE
BUG with restricted BoundaryTriangulation?

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#380]
Hi @fverdugo,

after updating `GridapDistributed.jl` to point to the most recent version of `Gridap.jl` master (i.e., commit 5d8ba281f8e96c63235be59a5821c7eda23ac5bf at the moment of writing this), I found that the test `DistributedPoissonDGTests.jl` of `GridapDistributed.jl` is now broken.

In particular, an `AssertionError` is internally thrown from `Gridap.jl` when executing this line of `DistributedPoissonDGTests.jl`:
[click here](https://github.com/gridap/GridapDistributed.jl/blob/168f50fe95019a0a114ff9c6cae0665db6fbc4f7/test/DistributedPoissonDGTests.jl#L113) (i.e., with  `OwnedCellsStrategy`). 

You can find the full stack trace of the exception here: [click here](https://travis-ci.com/github/gridap/GridapDistributed.jl/jobs/377453027#L887).

Note that the error is related to the evaluation of the linear boundary form `l_Γd(v) = (γ / h) * v * ud - (bn⋅∇(v)) * ud` with the boundary triangulation resulting from restricting the boundary triangulation of the subdomain to the cells owned by it.

I just found the error. I am aware that it is very hard to understand the cause of an error without debugging it, but before digging more deeply into it (i.e., understanding the error via debugging, finding a reproducer, etc.), I prefer to double-check if the error message tells you something about the cause of the error.  

Any insight? If not, I will work deeper into the issue, and come back to you with a detailed reproducer. 

Thanks!

**Comment by fverdugo** [comment]
Can you provide a MWE, if possible without depending on GridapDistributed?

**Comment by amartinhuertas** [comment]
> Can you provide a MWE, if possible without depending on GridapDistributed?

Ok, if the error message does not ring a bell, I will work out a small reproducer and come back to you.

**Comment by amartinhuertas** [comment]
I have the reproducer! See the code below. In particular, the issue documented above is produced within the last line of code.

I would say that the issue is here:

https://github.com/gridap/Gridap.jl/blob/master/src/CellData/CellFields.jl#L306

`cm` is of size 12, while `cf1` is of size 4 (the restriction of the boundary triangulation to the 4 facets in locally owned cells).

```julia
using Gridap
using Gridap.Geometry
using Gridap.FESpaces
domain = (0, 1, 0, 1)
cells = (3, 3)
model = CartesianDiscreteModel(domain, cells)

h = (domain[2] - domain[1]) / cells[1]
γ = 10
ud(x) = zero(x[1])
a_Γd(u, v) = (γ / h) * v * u - v * (bn⋅∇(u)) - (bn⋅∇(v)) * u
l_Γd(v) = (γ / h) * v * ud - (bn⋅∇(v)) * ud


# FE Spaces
order = 2
V = FESpace(
    valuetype = Float64,
    reffe = :Lagrangian,
    order = order,
    model = model,
    conformity = :L2,
)

U = TrialFESpace(V)

btrian=BoundaryTriangulation(model)
cell_to_oldcell=[1,2,3,6]
btrian=TriangulationPortion(btrian,cell_to_oldcell)
bn = get_normal_vector(btrian)
bquad = CellQuadrature(btrian, 2*order)
t_Γd = AffineFETerm(a_Γd, l_Γd, btrian, bquad)

 # Assembly
op = AffineFEOperator(U,V,t_Γd)
```

**Comment by amartinhuertas** [comment]
Hi @fverdugo, 

thanks for your work! 

After your bug-fix, `DistributedPoissonDGTests.jl` is now passing! (https://travis-ci.com/github/gridap/GridapDistributed.jl/builds/181576238#L915)

However, there is still an (I would say unrelated) issue with `DistributedStokesTests.jl` (https://travis-ci.com/github/gridap/GridapDistributed.jl/builds/181576238#L944). I will investigate further the cause of the failed test, and open a separate issue in `Gridap.jl` if required.

@amartinhuertas

**Comment by amartinhuertas** [comment]
> Hi @fverdugo,
> thanks for your work!
> After your bug-fix, DistributedPoissonDGTests.jl is now passing! (https://travis-ci.com/github/gridap/GridapDistributed.jl/builds/181576238#L915)
>
>However, there is still an (I would say unrelated) issue with DistributedStokesTests.jl (https://travis->ci.com/github/gridap/GridapDistributed.jl/builds/181576238#L944). I will investigate further the cause of the failed test, and > open a separate issue in Gridap.jl if required.
> @amartinhuertas

Forget about the post above. All `GridapDistributed.jl` are now passing (on my local machine). I still have to understand what it's going on Travis, seems to be a missconfiguration of the Package manager, that is using the latest registered version of Gridap.jl, instead of the want I am pointing to explicitly from `Manifest.toml` (i.e. the latest commit in #master). 

Closing the issue. Thanks for solving this!

**Comment by fverdugo** [comment]
Perfect. If you want to use Gridap#master on travis, consider something like:

```
# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
  - 1.5
before_script:
  - julia --project=. -e 'using Pkg; Pkg.add(PackageSpec(name="Gridap", rev="master"))'
notifications:
  email:
    on_success: never
    on_failure: always
jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.add(PackageSpec(name="Gridap", rev="master"))'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();Pkg.build()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
```
